# Generated by Django 4.1.6 on 2024-06-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_student_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.CharField(max_length=20),
        ),
    ]
