# Generated by Django 4.1.6 on 2024-06-29 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_availability_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduling.subject'),
        ),
    ]
