# Generated by Django 4.1.6 on 2024-06-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_availability_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
