# Generated by Django 4.1.6 on 2024-07-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_alter_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='student',
            name='free_time',
        ),
        migrations.AddField(
            model_name='student',
            name='friday_free_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='monday_free_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='saturday_free_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='sunday_free_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='thursday_free_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='tuesday_free_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='wednesday_free_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
