# Generated by Django 4.1.6 on 2024-07-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_remove_student_day_of_week_remove_student_free_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='friday_free_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='monday_free_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='saturday_free_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sunday_free_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='thursday_free_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='tuesday_free_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='wednesday_free_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
