# Generated by Django 4.1.6 on 2024-07-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_alter_student_friday_free_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='times_per_week',
            field=models.IntegerField(default=7),
        ),
    ]
